version: "3"

services:
  nginx:
    build: nginx
    container_name: nginx
    links:
      - flask
    ports:
      - "8080:80"
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      #todo:logは後でcontainerでまとめる
      - /tmp/nginx_log:/var/log/nginx

  flask:
    build: .
    container_name: flask
    ports:
      - "5000:5000"
    environment:
      #      ENV: PROD
      ENV: DEV
    volumes:
      - .:/introdon
    depends_on:
      - db
    links:
      - db

  db:
    #    image: mariadb:latest
    build: db
    container_name: mariadb
    ports:
      - "53306:3306"
    environment:
      MYSQL_DATABASE: introdon
    env_file: ./db/envfile #passwordは別ファイルでignore

#todo:log containerを建ててlogを集約する
#todo:dbのデータ永続化を実装する
