version: "3"

services:
  nginx:
    build: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker_data/log/nginx:/var/log/nginx
    depends_on:
      - flask
    networks:
      - front

  flask:
    build: .
    container_name: flask
    environment:
      # PROD, DEV, TEST
      FLASK_ENV: PROD
    volumes:
      - .:/introdon
      - ./docker_data/log/flask/gunicorn_access.log:/var/log/gunicorn_access.log
      - ./docker_data/log/flask/gunicorn_error.log:/var/log/gunicorn_error.log
    depends_on:
      - db
      - db_test
    networks:
      - front
      - back
      - test
    expose:
      - 5000

  db:
    build: db
    container_name: mariadb
    ports:
      - "53306:3306"
    volumes:
      - ./db/my.conf:/etc/mysql/conf.d/my.cnf
      - ./docker_data/mysql:/var/lib/mysql
      - ./docker_data/log/mysql:/var/log/mysql
    networks:
      - back
    environment:
      MYSQL_DATABASE: introdon
    env_file: ./db/envfile #password記載のためignore

  db_test:
    build: db
    container_name: mariadb_test
    ports:
      - "63306:3306"
    volumes:
      - ./db/my.conf:/etc/mysql/conf.d/my.cnf
    networks:
      - test
    environment:
      MYSQL_DATABASE: introdon_test
    env_file: ./db/envfile #password記載のためignore

networks:
  front:
    driver: bridge
  back:
    driver: bridge
  test:
    driver: bridge
